### ISSUE TITLE
How do you stub `.subscribe`?

### ISSUE THREAD

**Issue by LimeBlast** [krisleech/wisper-rspec#12]
Sorry, me again, I'm having some trouble figuring out how to stub a call to a subscriber. Here is what I've got so far:

```ruby
class PresentationsController < ApplicationController
  def create
    form = CreatePresentationForm.new(params.fetch(:create_presentation_form))

    command = CreatePresentation.new(form)

    command.subscribe(PresentationNotifier.new)

    command.on(:create_presentation_successful) { |result| redirect_to presentation_path(result) }
    command.on(:create_presentation_failed)     { |result| @form = result; render action: :new }

    command.call
  end
end
```

```ruby
require 'rails_helper'
require 'wisper/rspec/stub_wisper_publisher'

RSpec.describe PresentationsController, type: :controller do
  describe 'POST #create' do
    let(:form_class) { class_double('CreatePresentationForm').as_stubbed_const }
    let(:form_object) { double }

    before :each do
      expect(form_class).to receive(:new).and_return(form_object)
    end

    context 'create_presentation_successful' do
      let(:result) { double('Presentation', id: 1) }

      before do
        stub_wisper_publisher('CreatePresentation', :call, :create_presentation_successful, result)
        post :create, create_presentation_form: {}
      end

      it 'redirects' do
        expect(response).to redirect_to(presentation_path(result))
      end
    end

    context 'create_presentation_failed' do
      let(:result) { double }

      before do
        stub_wisper_publisher('CreatePresentation', :call, :create_presentation_failed, result)
        post :create, create_presentation_form: {}
      end

      it 'assigns result to @form' do
        expect(assigns(:form)).to eq result
      end

      it 'renders :new template' do
        expect(controller).to render_template(:new)
      end
    end
  end
end
```

This all works fine, with all the tests passing, except for the fact that `PresentationNotifier.new.create_presentation_successful()` us being called, where as what I'd rather have is a test that proves the subscriber is subscribed without it being called.

I have looked at the readme, and so far as I can tell, [this is the bit I should be looking at](https://github.com/krisleech/wisper-rspec#using-message-expections), but I can't figure out the code I need.

Can you point me in the right direction please? Thank you.

**Comment by krisleech** [comment]
I've never used `stub_wisper_publisher`, so unfortunately I can't help there.

The bit you linked to is standard rspec. I don't think `expect(listener).to receive(:an_event)` will actually call the method it expects to receive unless you add `.and_call_original` to the end.  I guess somehow you need to stub `PresentationNotifer` instances to be null objects doubles.

What I usually do for my controller specs is just assert that my "service" was called correctly for a given request, I don't check what events are broadcast. In the specs for the service I assert that the correct events are broadcast based on given inputs.

**Comment by LimeBlast** [comment]
I think it was having a bit of a brain-fart when I was looking at this before, because I think I've figured it out. I've added another let:

    let(:presentation_notifier) { class_double('PresentationNotifier').as_stubbed_const }

and added an expect line to my `before` block:

    expect(presentation_notifier).to receive(:new)

And that all appears to be working as intended. :)
