### ISSUE TITLE
Release new gem version with argument matching

### ISSUE THREAD

**Issue by SFEley** [krisleech/wisper-rspec#2]
This is a good testing suite, but I have a need for the broadcast argument matchers from pull request #1. The current version of the gem is 0.0.1 and this behavior isn't included yet. 

I can refer to this Github repo in my Gemfile of course, but I prefer not to do that with any library for very long. Would you be willing to release a new version of this gem with the new behavior?

**Comment by krisleech** [comment]
done :)
