### ISSUE TITLE
Allow broadcast matcher scoping

### ISSUE THREAD

**Issue by bradleyayers** [krisleech/wisper-rspec#24]
I avoid namespacing in my events, e.g. `user_created` vs `created`. However this means that when using the broadcast matcher I may accidentally capture the wrong event. I would like an additional matcher mechanism to allow the `expect { … }.to broadcast(:created)` pattern to support providing a scope, e.g.

```
expect { … }.to broadcast(:created).scope(:User)
```

**Comment by krisleech** [comment]
Can you describe you problem a little more, maybe an example would help, do you broadcast a "created" event many times from the same publisher within the same spec? If so, how do you distinguish between those events in your (production/non-test) code?

**Comment by bradleyayers** [comment]
I've switched away from wisper, so I no longer need this issue.
