### ISSUE TITLE
"publish" alias not available in latest RubyGems release

### ISSUE THREAD

**Issue by zebogen** [krisleech/wisper-rspec#25]
I'd like to make use of the `publish` alias for the `broadcast` matcher, but it's not in the most recent RubyGems release. Can you put out another release?

**Comment by krisleech** [comment]
I'd bet it is because `publish` was removed in Wisper 2.0, so you can only use `broadcast` thus this matches the wording. Are you using an older version of Wisper?

**Comment by zebogen** [comment]
`publish` was added as an alias for the `broadcast` matcher in this commit: https://github.com/krisleech/wisper-rspec/commit/8af4ad3f1de8c6a67ebeda6b7b066efe87dfab94

It just hasn't been released.

**Comment by krisleech** [comment]
Sorry, I misread you're original comment. I'll release a new version in the next few days.

**Comment by krisleech** [comment]
v1.0.0 released :smile:
