### ISSUE TITLE
Delete line 17 in your gemspec file ...

### ISSUE THREAD

**Issue by MadBomber** [krisleech/wisper-rspec#27]
Line 17 in your gemspec file reads:
 spec.executables = spec.files.grep(%r{^bin/}) { |f| File.basename(f) }

Your `bin` directory contains nothing special - just generic stuff.  There is no reason to pollute my workstations PATH with generic stuff like this.... which conflicts with every other gem author's generic junk that they forgot to disable in their gemspec.

-- gemspec police :)

**Comment by krisleech** [comment]
:+1:  send me a PR and I'll merge.
