### ISSUE TITLE
undefined local variable or method `publisher'

### ISSUE THREAD

**Issue by aaldrich** [krisleech/wisper-rspec#36]
I can't figure out how to get past this error. I've followed the instructions but I keep getting the error "undefined local variable or method `publisher'" whenever I run my specs.

I've added the following to my spec_helper.rb

```
RSpec::configure do |config|
  config.include(Wisper::RSpec::BroadcastMatcher)
end
```

In my test I've written a test like this

```
it "should broadcast a message for each integration type" do
  expect { publisher.execute }.to broadcast(:facebook_pixel_subscriber_created)
  SubscriberSubscriber.new.perform(@input_message)
end
```

I always get the error as shown here
<img width="1174" alt="Screen Shot on 2020-05-17 at 01-02-24" src="https://user-images.githubusercontent.com/134402/82137063-2523f680-97da-11ea-91d8-41fbbb0e46ef.png">

Any ideas?

**Comment by oscarada87** [comment]
I think `publisher` must be a class instance variable belongs to your publisher class.

**Comment by krisleech** [comment]
This doesn't look to be related to wisper-rspec.
