### ISSUE TITLE
Getting undefined method broadcast in spec

### ISSUE THREAD

**Issue by cored** [krisleech/wisper-rspec#5]
`block (3 levels) in <top (required)>': undefined method `broadcast' for #<Class:0x007f2908a38350> (NoMethodError)

I added  `require 'wisper/rspec/matchers'` to my spec_helper. And I'm trying to assert on `it { publisher.update }.to broadcast(:event)` . 

Am I doing something wrong?

**Comment by krisleech** [comment]
I've never tried the one liner syntax, can you try it as `expect { publisher.update }.to broadcast(:event)` please.

**Comment by krisleech** [comment]
Also this gem is only needed when/if you use Wisper 2.0.0.rc1. The matchers are built in to Wisper ~1.0.

**Comment by musaffa** [comment]
I get this error in the `spec_helper.rb`:

`uninitialized constant Wisper::Rspec::BroadcastMatcher (NameError)`

This problem has nothing to do with expect/it format. It simply cannot find the matcher. It works without any problem in Wisper ~1.0.

**Comment by krisleech** [comment]
@musaffa have you included `gem 'wisper-rspec'` in the Gemfile?

**Comment by musaffa** [comment]
Yes i did.

**Comment by krisleech** [comment]
Can you provide a few lines of the stacktrace please.

**Comment by krisleech** [comment]
@musaffa I setup a sample project here: https://github.com/krisleech/wispering

It seems to work okay, can you clone the repo and try for yourself.

**Comment by musaffa** [comment]
Your gem is fine. In wisper ~1.0 the matcher was included like this: 
```Ruby
config.include(Wisper::Rspec::BroadcastMatcher)
```
But now in wisper-rspec:
```Ruby
config.include(Wisper::RSpec::BroadcastMatcher)
```
A capital S!

**Comment by krisleech** [comment]
Glad you sorted it :)
