### ISSUE TITLE
idea: when a broadcast expectation fails, spell out what was broadcast

### ISSUE THREAD

**Issue by sockmonk** [krisleech/wisper-rspec#7]
First of all, I'm just starting to use the wisper gem in a large legacy project, and it's a big help in untangling some messy code and separating concerns better. So thank you.

When I have an expectation like
    expect { publisher.execute }.to broadcast(:something)

And it fails, it would be nice to know what event(s) it did broadcast. So the failure message might look something like:

```
expected publisher to broadcast something event
publisher broadcasted these events: failure
```

This would make it easier to track down what went wrong, especially when I have several different possible events that could be broadcast in different situations. Thanks.

**Comment by barrywark** [comment]
+1

**Comment by krisleech** [comment]
Good idea, do you fancy having a go at a PR? I can help out if you get stuck.

**Comment by krisleech** [comment]
Hi - Did you manage to look at this? Cheers.

**Comment by Morred** [comment]
+1

**Comment by sockmonk** [comment]
I did a pull request, which was merged to master back in August 2015. There has been no release since then, but you can always point to master to get this and other improvements.
